version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: spectrum-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_POSTGRES_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spectrum-network

  mongo-db:
    image: mongo:7.0
    container_name: spectrum-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      DB_MONGO_USER: ${DB_MONGO_USER}
      DB_MONGO_PASSWORD: ${DB_MONGO_PASSWORD}
      DB_MONGO_DROPS_NAME: ${DB_MONGO_DROPS_NAME}
      DB_MONGO_SOCIAL_NAME: ${DB_MONGO_SOCIAL_NAME}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    networks:
      - spectrum-network

  service-social:
    build:
      context: .
      dockerfile: services/service-social/Dockerfile
    container_name: spectrum-social
    restart: always
    ports:
      - "9091:9091"
    depends_on:
      - mongo-db
    networks:
      - spectrum-network

  service-drops:
    build:
      context: .
      dockerfile: services/service-drops/Dockerfile
    container_name: spectrum-sorteo
    restart: always
    ports:
      - "9090:9090"
    depends_on:
      - mongo-db
    networks:
      - spectrum-network

  api-core:
    build:
      context: .
      dockerfile: services/api-core/Spectrum.API/Dockerfile
    container_name: spectrum-api-core
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - postgres-db
      - service-social
      - service-drops
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Port=5432;Database=${DB_POSTGRES_NAME};Username=${DB_POSTGRES_USER};Password=${DB_POSTGRES_PASSWORD};
      - GrpcSettings__DropsServiceUrl=http://service-drops:9090
      - GrpcSettings__SocialServiceUrl=http://service-social:9091
      - DemoSeed__MongoConnectionString=mongodb://${MONGO_INITDB_ROOT_USER}:${MONGO_INITDB_ROOT_PASSWORD}@mongo-db:27017/?authSource=admin
      - DemoSeed__SocialMongoConnectionString=mongodb://${MONGO_INITDB_ROOT_USER}:${MONGO_INITDB_ROOT_PASSWORD}@mongo-db:27017/${DB_MONGO_SOCIAL_NAME}?authSource=admin
      - DemoSeed__DropsMongoConnectionString=mongodb://${MONGO_INITDB_ROOT_USER}:${MONGO_INITDB_ROOT_PASSWORD}@mongo-db:27017/${DB_MONGO_DROPS_NAME}?authSource=admin
    networks:
      - spectrum-network

volumes:
  postgres_data:
  mongo_data:
  
networks:
  spectrum-network:
    driver: bridge
