using System.ComponentModel.DataAnnotations;

namespace Spectrum.API.Dtos.Media
{
    /// <summary>
    /// Response DTO containing the necessary identifiers to start uploading video chunks.
    /// </summary>
    public class MultipartInitResponseDto
    {
        /// <summary>
        /// Multipart upload session identifier generated by AWS S3.
        /// </summary>
        public string UploadId { get; set; } = string.Empty;

        /// <summary>
        /// Storage object key that uniquely identifies the video file in S3.
        /// </summary>
        public string KeyName { get; set; } = string.Empty;
    }

    /// <summary>
    /// Request DTO for completing a multipart upload, containing all chunk identifiers and database record metadata.
    /// </summary>
    public class CompleteUploadRequestDto
    {
        /// <summary>
        /// Active multipart upload session identifier.
        /// </summary>
        [Required]
        public string UploadId { get; set; } = string.Empty;

        /// <summary>
        /// Storage object key associated with the multipart upload.
        /// </summary>
        [Required]
        public string KeyName { get; set; } = string.Empty;

        /// <summary>
        /// Display title of the clip.
        /// </summary>
        [Required]
        [StringLength(100, MinimumLength = 3)]
        public string Title { get; set; } = string.Empty;

        /// <summary>
        /// Optional description provided by the uploader.
        /// </summary>
        [StringLength(500)]
        public string? Description { get; set; }

        /// <summary>
        /// RAWG identifier of the game associated with the clip.
        /// </summary>
        [Range(1, int.MaxValue)]
        public int GameId { get; set; }

        /// <summary>
        /// Collection of uploaded chunk identifiers required to assemble the final video.
        /// </summary>
        [MinLength(1)]
        public List<PartEtagDto> Etags { get; set; } = new();
    }

    /// <summary>
    /// Represents a single chunk's sequence number and its AWS ETag identifier.
    /// </summary>
    public class PartEtagDto
    {
        /// <summary>
        /// Sequential chunk number within the multipart upload.
        /// </summary>
        public int PartNumber { get; set; }

        /// <summary>
        /// AWS S3 ETag value returned after uploading the chunk.
        /// </summary>
        public string ETag { get; set; } = string.Empty;
    }
}
