namespace Spectrum.API.Dtos.Reviews
{
    /// <summary>
    /// Review comment returned by the API.
    /// </summary>
    public class ReviewCommentResponseDto
    {
        /// <summary>
        /// Comment identifier generated by the social service.
        /// </summary>
        public string Id { get; set; } = string.Empty;

        /// <summary>
        /// Author identifier.
        /// </summary>
        public Guid UserId { get; set; }

        /// <summary>
        /// Associated review identifier.
        /// </summary>
        public Guid ReviewId { get; set; }

        /// <summary>
        /// Comment content.
        /// </summary>
        public string Content { get; set; } = string.Empty;

        /// <summary>
        /// UTC publication date.
        /// </summary>
        public DateTime PublishedAt { get; set; }

        /// <summary>
        /// Author username.
        /// </summary>
        public string Username { get; set; } = string.Empty;

        /// <summary>
        /// Author profile picture URL.
        /// </summary>
        public string UserProfilePicture { get; set; } = string.Empty;

        /// <summary>
        /// Indicates whether the comment belongs to the authenticated user.
        /// </summary>
        public bool IsOwnComment { get; set; }

        /// <summary>
        /// Indicates whether the authenticated user can delete the comment.
        /// </summary>
        public bool CanDelete { get; set; }
    }
}
